{% set version = "0.14.0" %}

{% set PYTHON = PYTHON | default("$PYTHON") %}

package:
  name: ariadne-codegen
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/a/ariadne-codegen/ariadne_codegen-{{ version }}.tar.gz
    sha256: d5b15470195c3858b88a2bae855b5c04602ffae40228077b6cfb26a57d3f14f6
  - folder: src
    url: https://github.com/mirumee/ariadne-codegen/archive/refs/tags/{{ version }}.tar.gz
    sha256: 86d79970c8260fa8292e40ada695babcf47560d6ac599611d039daedaae8543c

build:
  number: 1
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - ariadne-codegen = ariadne_codegen.main:main

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - autoflake
    - black
    - click >=8.1,<9.0
    - graphql-core >=3.2.0,<3.3
    - httpx >=0.23,<1.0
    - isort
    - pydantic >=2.0.0,<3.0.0
    - toml >=0.10,<1.0
  run_constrained:
    - websockets >=11.0,<12.0

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - ariadne_codegen
  commands:
    - pip check
    - ariadne-codegen --help

outputs:
  - name: ariadne-codegen

  - name: ariadne-codegen-with-websockets
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("ariadne-codegen", exact=True) }}
        - websockets
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - ariadne_codegen
      commands:
        - pip check
        - ariadne-codegen --help

  - name: ariadne-codegen-with-opentelemetry
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("ariadne-codegen", exact=True) }}
        - opentelemetry-api
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - ariadne_codegen
      commands:
        - pip check
        - ariadne-codegen --help

  - name: ariadne-codegen-with-all
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("ariadne-codegen-with-opentelemetry", exact=True) }}
        - {{ pin_subpackage("ariadne-codegen-with-websockets", exact=True) }}
    test:
      source_files:
        - src/tests
      requires:
        - ariadne
        - freezegun
        - pip
        - pytest
        - pytest-asyncio
        - pytest-httpx
        - pytest-mock
        - requests-toolbelt
        - python {{ python_min }}
      imports:
        - ariadne_codegen
      commands:
        - pip check
        - ariadne-codegen --help
        # doesn't handle windows slashes
        {% set skips = '-k "not invalid_file"' %}  # [win]
        {% set skips = '' %}                       # [unix]
        - cd src && pytest -vv --tb=long --color=yes {{ skips }}

about:
  home: https://github.com/mirumee/ariadne-codegen
  summary: Generate fully typed GraphQL client from schema, queries and mutations!
  license: BSD-3-Clause
  license_file: dist/LICENSE

extra:
  feedstock-name: ariadne-codegen
  recipe-maintainers:
    - ytausch
    - bollwyvl
