{% set version = "0.15.2" %}

{% set PYTHON = PYTHON | default("$PYTHON") %}

package:
  name: ariadne-codegen
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/a/ariadne-codegen/ariadne_codegen-{{ version }}.tar.gz
    sha256: 44f0a3231f8bd201e908094adc7db564a04a047a14b2c13f6a94387cff5a8ab7
  - folder: src
    url: https://github.com/mirumee/ariadne-codegen/archive/refs/tags/{{ version }}.tar.gz
    sha256: 539e0de73f80968e3e1530b09d5ffae6c746f41000acc859c8e409adb9f8bd5c

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - ariadne-codegen = ariadne_codegen.main:main

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - autoflake
    - black
    - click >=8.1,<9.0
    - graphql-core >=3.2.0,<3.3
    - httpx >=0.23,<1.0
    - isort
    - pydantic >=2.0.0,<3.0.0
    - toml >=0.10,<1.0
  run_constrained:
    - websockets >=11.0,<12.0

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - ariadne_codegen
  commands:
    - pip check
    - ariadne-codegen --help

outputs:
  - name: ariadne-codegen

  - name: ariadne-codegen-with-websockets
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("ariadne-codegen", exact=True) }}
        - websockets
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - ariadne_codegen
      commands:
        - pip check
        - ariadne-codegen --help

  - name: ariadne-codegen-with-opentelemetry
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("ariadne-codegen", exact=True) }}
        - opentelemetry-api
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - ariadne_codegen
      commands:
        - pip check
        - ariadne-codegen --help

  - name: ariadne-codegen-with-all
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("ariadne-codegen-with-opentelemetry", exact=True) }}
        - {{ pin_subpackage("ariadne-codegen-with-websockets", exact=True) }}
    test:
      files:
        - run_test_all.py
      source_files:
        - src/tests
      requires:
        - coverage
        - ariadne
        - freezegun
        - pip
        - pytest
        - pytest-asyncio
        - pytest-httpx
        - pytest-mock
        - python {{ python_min }}
        - requests-toolbelt
        # see https://github.com/mirumee/ariadne-codegen/issues/335
        - httpx <0.28
      imports:
        - ariadne_codegen
      commands:
        - pip check
        - ariadne-codegen --help
        - python run_test_all.py

about:
  home: https://github.com/mirumee/ariadne-codegen
  summary: Generate fully typed GraphQL client from schema, queries and mutations!
  license: BSD-3-Clause
  license_file: dist/LICENSE

extra:
  feedstock-name: ariadne-codegen
  recipe-maintainers:
    - ytausch
    - bollwyvl
